version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=wordpress
      - MARIADB_DATABASE=wordpress
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  wordpress:
    image: vhphan/pposhipping-wpr-web:php7.4-apache
    ports:
      - '82:8080'
      - '444:8443'
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local
